-- ====================================================================
-- RETAIL SALES ANALYTICS PLATFORM
-- SQL Analytics Queries
-- ====================================================================
-- Database : RETAIL_DB
-- Schema   : RETAIL_SCHEMA
-- Tables   : CUSTOMERS, PRODUCTS, ORDERS
-- Views    : VW_MONTHLY_SALES, VW_CUSTOMER_ANALYTICS, VW_PRODUCT_PERFORMANCE
-- ====================================================================
-- Queries organized by SQL concept:
--   01-05  Basic KPIs
--   06-10  Aggregations
--   11-14  GROUP BY & HAVING
--   15-18  JOINs
--   19-21  Subqueries
--   22-24  Views
--   25-27  CTEs
--   28-33  Window Functions (Ranking)
--   34-36  Window Functions (Running Totals & Moving Average)
--   37-38  Customer Lifetime Value
--   39-40  Advanced Business Analytics
-- ====================================================================

USE DATABASE RETAIL_DB;
USE SCHEMA   RETAIL_SCHEMA;
USE WAREHOUSE RETAIL_WH;



-- ====================================================================
-- SECTION 1: BASIC KPIs
-- SQL Concept: SELECT, aggregate functions (COUNT, SUM, AVG)
-- ====================================================================


-- Query 01: Total Revenue
-- Business Question: What is the total revenue generated by the business?
-- ====================================================================
SELECT
    ROUND(SUM(TOTAL_AMOUNT), 2)   AS TOTAL_REVENUE_INR
FROM
    ORDERS
WHERE
    ORDER_STATUS != 'Cancelled';


-- Query 02: Total Orders Placed
-- Business Question: How many orders have been placed in total?
-- ====================================================================
SELECT
    COUNT(DISTINCT ORDER_ID)   AS TOTAL_ORDERS
FROM
    ORDERS;


-- Query 03: Total Unique Customers
-- Business Question: How many unique customers have placed at least one order?
-- ====================================================================
SELECT
    COUNT(DISTINCT CUSTOMER_ID)   AS TOTAL_CUSTOMERS_WITH_ORDERS
FROM
    ORDERS;


-- Query 04: Total Products in Catalog
-- Business Question: How many products are available in the system?
-- ====================================================================
SELECT
    COUNT(DISTINCT PRODUCT_ID)   AS TOTAL_PRODUCTS,
    COUNT(DISTINCT CATEGORY)     AS TOTAL_CATEGORIES
FROM
    PRODUCTS;


-- Query 05: Average Order Value (AOV)
-- Business Question: What is the average revenue per order?
-- AOV = Total Revenue / Total Orders (excluding cancelled)
-- ====================================================================
SELECT
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    ROUND(SUM(TOTAL_AMOUNT), 2)     AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT), 2)     AS AVG_ORDER_VALUE
FROM
    ORDERS
WHERE
    ORDER_STATUS != 'Cancelled';



-- ====================================================================
-- SECTION 2: AGGREGATIONS
-- SQL Concept: SUM, COUNT, AVG, MIN, MAX with GROUP BY
-- ====================================================================


-- Query 06: Revenue by Category
-- Business Question: Which product categories drive the most revenue?
-- ====================================================================
SELECT
    P.CATEGORY,
    COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
    SUM(O.QUANTITY)                     AS TOTAL_UNITS_SOLD,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_REVENUE,
    ROUND(AVG(O.TOTAL_AMOUNT), 2)       AS AVG_ORDER_VALUE
FROM
    ORDERS O
    JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.CATEGORY
ORDER BY
    TOTAL_REVENUE DESC;


-- Query 07: Revenue by Region
-- Business Question: Which geographic region generates the most revenue?
-- ====================================================================
SELECT
    C.REGION,
    COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
    COUNT(DISTINCT O.CUSTOMER_ID)       AS UNIQUE_CUSTOMERS,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_REVENUE
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.REGION
ORDER BY
    TOTAL_REVENUE DESC;


-- Query 08: Revenue by State (Top 15)
-- Business Question: Which states contribute the most to our revenue?
-- ====================================================================
SELECT
    C.STATE,
    C.REGION,
    COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
    COUNT(DISTINCT O.CUSTOMER_ID)       AS UNIQUE_CUSTOMERS,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_REVENUE
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.STATE, C.REGION
ORDER BY
    TOTAL_REVENUE DESC
LIMIT 15;


-- Query 09: Monthly Sales Trend
-- Business Question: How does revenue change month over month?
-- ====================================================================
SELECT
    YEAR(ORDER_DATE)                    AS YEAR,
    MONTH(ORDER_DATE)                   AS MONTH,
    MONTHNAME(ORDER_DATE)               AS MONTH_NAME,
    COUNT(DISTINCT ORDER_ID)            AS TOTAL_ORDERS,
    ROUND(SUM(TOTAL_AMOUNT), 2)         AS MONTHLY_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT), 2)         AS AVG_ORDER_VALUE
FROM
    ORDERS
WHERE
    ORDER_STATUS != 'Cancelled'
GROUP BY
    YEAR(ORDER_DATE),
    MONTH(ORDER_DATE),
    MONTHNAME(ORDER_DATE)
ORDER BY
    YEAR, MONTH;


-- Query 10: Payment Method Distribution
-- Business Question: Which payment methods do customers prefer?
-- ====================================================================
SELECT
    PAYMENT_METHOD,
    COUNT(DISTINCT ORDER_ID)            AS TOTAL_ORDERS,
    ROUND(SUM(TOTAL_AMOUNT), 2)         AS TOTAL_REVENUE,
    ROUND(COUNT(*) * 100.0 /
          SUM(COUNT(*)) OVER (), 2)     AS ORDER_SHARE_PCT
FROM
    ORDERS
WHERE
    ORDER_STATUS != 'Cancelled'
GROUP BY
    PAYMENT_METHOD
ORDER BY
    TOTAL_ORDERS DESC;



-- ====================================================================
-- SECTION 3: GROUP BY & HAVING
-- SQL Concept: Filtering aggregated results with HAVING clause
-- ====================================================================


-- Query 11: High-Value Customers (Spent > 50,000 INR)
-- Business Question: Which customers have spent more than 50,000 rupees?
-- SQL Concept: HAVING filters after GROUP BY (WHERE filters before)
-- ====================================================================
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_SPENT
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.CUSTOMER_ID, C.CUSTOMER_NAME, C.CITY, C.STATE
HAVING
    SUM(O.TOTAL_AMOUNT) > 50000
ORDER BY
    TOTAL_SPENT DESC;


-- Query 12: Repeat Customers (More Than 3 Orders)
-- Business Question: Which customers are our most loyal repeat buyers?
-- SQL Concept: HAVING with COUNT
-- ====================================================================
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.REGION,
    COUNT(DISTINCT O.ORDER_ID)          AS ORDER_COUNT,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_SPENT
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.CUSTOMER_ID, C.CUSTOMER_NAME, C.REGION
HAVING
    COUNT(DISTINCT O.ORDER_ID) > 3
ORDER BY
    ORDER_COUNT DESC;


-- Query 13: Categories with Average Order Value > 10,000
-- Business Question: Which categories command premium order values?
-- SQL Concept: HAVING on AVG
-- ====================================================================
SELECT
    P.CATEGORY,
    COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
    ROUND(AVG(O.TOTAL_AMOUNT), 2)       AS AVG_ORDER_VALUE,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_REVENUE
FROM
    ORDERS O
    JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.CATEGORY
HAVING
    AVG(O.TOTAL_AMOUNT) > 10000
ORDER BY
    AVG_ORDER_VALUE DESC;


-- Query 14: Order Status Summary
-- Business Question: What percentage of orders are completed, cancelled, returned?
-- SQL Concept: GROUP BY with percentage calculation
-- ====================================================================
SELECT
    ORDER_STATUS,
    COUNT(ORDER_ID)                         AS ORDER_COUNT,
    ROUND(SUM(TOTAL_AMOUNT), 2)             AS TOTAL_AMOUNT,
    ROUND(COUNT(*) * 100.0 /
          SUM(COUNT(*)) OVER (), 2)         AS ORDER_SHARE_PCT
FROM
    ORDERS
GROUP BY
    ORDER_STATUS
ORDER BY
    ORDER_COUNT DESC;



-- ====================================================================
-- SECTION 4: JOINs
-- SQL Concept: INNER JOIN, LEFT JOIN to combine tables
-- ====================================================================


-- Query 15: Complete Order Details (3-Table JOIN)
-- Business Question: Show full order details with customer and product info.
-- SQL Concept: Multiple INNER JOINs across 3 tables
-- ====================================================================
SELECT
    O.ORDER_ID,
    O.ORDER_DATE,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    O.QUANTITY,
    O.UNIT_PRICE,
    O.DISCOUNT,
    O.TOTAL_AMOUNT,
    O.ORDER_STATUS,
    O.PAYMENT_METHOD
FROM
    ORDERS O
    INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    INNER JOIN PRODUCTS  P ON O.PRODUCT_ID  = P.PRODUCT_ID
ORDER BY
    O.ORDER_DATE DESC
LIMIT 100;


-- Query 16: Customers Who Have Never Ordered
-- Business Question: Which registered customers have never placed an order?
-- SQL Concept: LEFT JOIN with NULL check to find unmatched rows
-- ====================================================================
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.EMAIL,
    C.CITY,
    C.STATE,
    C.JOIN_DATE
FROM
    CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    O.ORDER_ID IS NULL
ORDER BY
    C.JOIN_DATE;


-- Query 17: Top 10 Revenue-Generating Customers (Full Profile)
-- Business Question: Who are our top 10 customers and where are they from?
-- SQL Concept: JOIN + GROUP BY + ORDER BY + LIMIT
-- ====================================================================
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.EMAIL,
    C.CITY,
    C.STATE,
    C.REGION,
    COUNT(DISTINCT O.ORDER_ID)      AS TOTAL_ORDERS,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)   AS TOTAL_REVENUE
FROM
    CUSTOMERS C
    INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.CUSTOMER_ID, C.CUSTOMER_NAME, C.EMAIL, C.CITY, C.STATE, C.REGION
ORDER BY
    TOTAL_REVENUE DESC
LIMIT 10;


-- Query 18: Revenue by City (Top 20)
-- Business Question: Which cities contribute the most revenue?
-- SQL Concept: JOIN with GROUP BY on city
-- ====================================================================
SELECT
    C.CITY,
    C.STATE,
    C.REGION,
    COUNT(DISTINCT O.ORDER_ID)      AS TOTAL_ORDERS,
    COUNT(DISTINCT C.CUSTOMER_ID)  AS UNIQUE_CUSTOMERS,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)  AS TOTAL_REVENUE
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.CITY, C.STATE, C.REGION
ORDER BY
    TOTAL_REVENUE DESC
LIMIT 20;



-- ====================================================================
-- SECTION 5: SUBQUERIES
-- SQL Concept: Nested SELECT inside WHERE / FROM clause
-- ====================================================================


-- Query 19: Orders Above Average Order Value
-- Business Question: Which orders are above the average order amount?
-- SQL Concept: Scalar subquery in WHERE clause
-- ====================================================================
SELECT
    O.ORDER_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    O.TOTAL_AMOUNT,
    ROUND((SELECT AVG(TOTAL_AMOUNT)
           FROM ORDERS
           WHERE ORDER_STATUS != 'Cancelled'), 2) AS AVG_ORDER_VALUE
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    JOIN PRODUCTS  P ON O.PRODUCT_ID  = P.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
    AND O.TOTAL_AMOUNT > (
        SELECT AVG(TOTAL_AMOUNT)
        FROM   ORDERS
        WHERE  ORDER_STATUS != 'Cancelled'
    )
ORDER BY
    O.TOTAL_AMOUNT DESC
LIMIT 20;


-- Query 20: Top Product per Category (Subquery approach)
-- Business Question: Which product generates the most revenue in each category?
-- SQL Concept: Correlated subquery
-- ====================================================================
SELECT
    P.CATEGORY,
    P.PRODUCT_NAME,
    P.BRAND,
    ROUND(SUM(O.TOTAL_AMOUNT), 2) AS CATEGORY_TOP_REVENUE
FROM
    PRODUCTS P
    JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.CATEGORY, P.PRODUCT_NAME, P.BRAND
HAVING
    SUM(O.TOTAL_AMOUNT) = (
        SELECT MAX(INNER_SUM.PRODUCT_REV)
        FROM (
            SELECT
                P2.CATEGORY,
                SUM(O2.TOTAL_AMOUNT) AS PRODUCT_REV
            FROM PRODUCTS P2
            JOIN ORDERS O2 ON P2.PRODUCT_ID = O2.PRODUCT_ID
            WHERE O2.ORDER_STATUS != 'Cancelled'
            GROUP BY P2.CATEGORY, P2.PRODUCT_ID
        ) INNER_SUM
        WHERE INNER_SUM.CATEGORY = P.CATEGORY
    )
ORDER BY
    P.CATEGORY;


-- Query 21: States with Above-Average Customer Count
-- Business Question: Which states have more customers than the national average?
-- SQL Concept: Subquery in HAVING clause
-- ====================================================================
SELECT
    STATE,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM
    CUSTOMERS
GROUP BY
    STATE
HAVING
    COUNT(DISTINCT CUSTOMER_ID) > (
        SELECT AVG(STATE_COUNT)
        FROM (
            SELECT COUNT(DISTINCT CUSTOMER_ID) AS STATE_COUNT
            FROM   CUSTOMERS
            GROUP BY STATE
        ) STATE_SUMMARY
    )
ORDER BY
    CUSTOMER_COUNT DESC;



-- ====================================================================
-- SECTION 6: VIEWS
-- SQL Concept: Using pre-built views for simplicity
-- ====================================================================


-- Query 22: Monthly Sales Dashboard (using VW_MONTHLY_SALES)
-- Business Question: Show the complete monthly sales trend.
-- SQL Concept: Querying a VIEW (abstraction layer)
-- ====================================================================
SELECT
    YEAR_MONTH,
    MONTH_NAME,
    TOTAL_ORDERS,
    UNIQUE_CUSTOMERS,
    TOTAL_REVENUE,
    AVG_ORDER_VALUE,
    TOTAL_UNITS_SOLD
FROM
    VW_MONTHLY_SALES
ORDER BY
    YEAR, MONTH;


-- Query 23: Customer Segments (using VW_CUSTOMER_ANALYTICS)
-- Business Question: How many customers fall into each spending segment?
-- SQL Concept: Aggregate over a VIEW
-- ====================================================================
SELECT
    CUSTOMER_SEGMENT,
    COUNT(CUSTOMER_ID)              AS CUSTOMER_COUNT,
    ROUND(SUM(TOTAL_SPENT), 2)      AS SEGMENT_REVENUE,
    ROUND(AVG(TOTAL_SPENT), 2)      AS AVG_SPEND_PER_CUSTOMER
FROM
    VW_CUSTOMER_ANALYTICS
GROUP BY
    CUSTOMER_SEGMENT
ORDER BY
    SEGMENT_REVENUE DESC;


-- Query 24: Product Performance Dashboard (using VW_PRODUCT_PERFORMANCE)
-- Business Question: Which products should the business promote more?
-- SQL Concept: VIEW with pre-calculated rankings
-- ====================================================================
SELECT
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    TOTAL_ORDERS,
    TOTAL_UNITS_SOLD,
    TOTAL_REVENUE,
    REVENUE_RANK,
    CATEGORY_RANK,
    OVERALL_CONTRIBUTION_PCT
FROM
    VW_PRODUCT_PERFORMANCE
WHERE
    REVENUE_RANK <= 20
ORDER BY
    REVENUE_RANK;



-- ====================================================================
-- SECTION 7: CTEs (Common Table Expressions)
-- SQL Concept: WITH clause for readable, reusable intermediate results
-- ====================================================================


-- Query 25: Customer Lifetime Value with CTE
-- Business Question: What is the total lifetime spend per customer?
-- SQL Concept: CTE for multi-step calculation
-- ====================================================================
WITH CUSTOMER_ORDERS AS (
    -- Step 1: Calculate customer-level metrics
    SELECT
        O.CUSTOMER_ID,
        COUNT(DISTINCT O.ORDER_ID)     AS TOTAL_ORDERS,
        SUM(O.TOTAL_AMOUNT)            AS LIFETIME_VALUE,
        MIN(O.ORDER_DATE)              AS FIRST_ORDER,
        MAX(O.ORDER_DATE)              AS LAST_ORDER
    FROM
        ORDERS O
    WHERE
        O.ORDER_STATUS != 'Cancelled'
    GROUP BY
        O.CUSTOMER_ID
),
CUSTOMER_PROFILE AS (
    -- Step 2: Join with customer master data
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.STATE,
        C.REGION,
        CO.TOTAL_ORDERS,
        ROUND(CO.LIFETIME_VALUE, 2)    AS CUSTOMER_LTV,
        CO.FIRST_ORDER,
        CO.LAST_ORDER,
        DATEDIFF('day', CO.FIRST_ORDER, CO.LAST_ORDER) AS ACTIVE_DAYS
    FROM
        CUSTOMERS C
        INNER JOIN CUSTOMER_ORDERS CO ON C.CUSTOMER_ID = CO.CUSTOMER_ID
)
-- Step 3: Show top customers by LTV
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    STATE,
    REGION,
    TOTAL_ORDERS,
    CUSTOMER_LTV,
    FIRST_ORDER,
    LAST_ORDER,
    ACTIVE_DAYS
FROM
    CUSTOMER_PROFILE
ORDER BY
    CUSTOMER_LTV DESC
LIMIT 20;


-- Query 26: Monthly Revenue Growth Percentage
-- Business Question: How is revenue growing month-over-month?
-- SQL Concept: CTE + LAG window function for growth calculation
-- ====================================================================
WITH MONTHLY_REV AS (
    SELECT
        TO_CHAR(ORDER_DATE, 'YYYY-MM')        AS YEAR_MONTH,
        YEAR(ORDER_DATE)                       AS YEAR,
        MONTH(ORDER_DATE)                      AS MONTH,
        ROUND(SUM(TOTAL_AMOUNT), 2)            AS MONTHLY_REVENUE
    FROM
        ORDERS
    WHERE
        ORDER_STATUS != 'Cancelled'
    GROUP BY
        TO_CHAR(ORDER_DATE, 'YYYY-MM'),
        YEAR(ORDER_DATE),
        MONTH(ORDER_DATE)
),
REVENUE_WITH_GROWTH AS (
    SELECT
        YEAR_MONTH,
        MONTHLY_REVENUE,
        LAG(MONTHLY_REVENUE) OVER (ORDER BY YEAR, MONTH) AS PREV_MONTH_REVENUE
    FROM
        MONTHLY_REV
)
SELECT
    YEAR_MONTH,
    MONTHLY_REVENUE,
    PREV_MONTH_REVENUE,
    CASE
        WHEN PREV_MONTH_REVENUE IS NULL OR PREV_MONTH_REVENUE = 0
            THEN NULL
        ELSE ROUND(
            (MONTHLY_REVENUE - PREV_MONTH_REVENUE) * 100.0 / PREV_MONTH_REVENUE, 2
        )
    END AS MOM_GROWTH_PCT
FROM
    REVENUE_WITH_GROWTH
ORDER BY
    YEAR_MONTH;


-- Query 27: Top 3 Products per Category (CTE + ROW_NUMBER)
-- Business Question: Which 3 products lead revenue in each category?
-- SQL Concept: CTE with ROW_NUMBER for top-N per group
-- ====================================================================
WITH PRODUCT_REVENUE AS (
    SELECT
        P.CATEGORY,
        P.PRODUCT_NAME,
        P.BRAND,
        COUNT(DISTINCT O.ORDER_ID)          AS TOTAL_ORDERS,
        ROUND(SUM(O.TOTAL_AMOUNT), 2)       AS TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY P.CATEGORY
            ORDER BY SUM(O.TOTAL_AMOUNT) DESC
        )                                   AS RANK_IN_CATEGORY
    FROM
        PRODUCTS P
        JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE
        O.ORDER_STATUS != 'Cancelled'
    GROUP BY
        P.CATEGORY, P.PRODUCT_NAME, P.BRAND
)
SELECT
    CATEGORY,
    RANK_IN_CATEGORY,
    PRODUCT_NAME,
    BRAND,
    TOTAL_ORDERS,
    TOTAL_REVENUE
FROM
    PRODUCT_REVENUE
WHERE
    RANK_IN_CATEGORY <= 3
ORDER BY
    CATEGORY, RANK_IN_CATEGORY;



-- ====================================================================
-- SECTION 8: WINDOW FUNCTIONS — RANKING
-- SQL Concept: RANK, DENSE_RANK, ROW_NUMBER, NTILE
-- ====================================================================


-- Query 28: Product Revenue Ranking using RANK()
-- Business Question: Rank all products by total revenue (gaps for ties)
-- SQL Concept: RANK() — skips rank numbers after ties
-- ====================================================================
SELECT
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)    AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(O.TOTAL_AMOUNT) DESC
    )                                AS REVENUE_RANK
FROM
    PRODUCTS P
    JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.PRODUCT_NAME, P.CATEGORY, P.BRAND
ORDER BY
    REVENUE_RANK;


-- Query 29: Customer Spending Rank using DENSE_RANK()
-- Business Question: Rank customers by spend (no gaps for ties)
-- SQL Concept: DENSE_RANK() — consecutive rank numbers even with ties
-- ====================================================================
SELECT
    C.CUSTOMER_NAME,
    C.STATE,
    C.REGION,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)   AS TOTAL_SPENT,
    DENSE_RANK() OVER (
        ORDER BY SUM(O.TOTAL_AMOUNT) DESC
    )                               AS SPENDING_RANK
FROM
    CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    C.CUSTOMER_NAME, C.STATE, C.REGION
ORDER BY
    SPENDING_RANK
LIMIT 25;


-- Query 30: Order Sequence per Customer using ROW_NUMBER()
-- Business Question: What was the 1st, 2nd, 3rd order placed by each customer?
-- SQL Concept: ROW_NUMBER() PARTITION BY customer — sequential numbering
-- ====================================================================
SELECT
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.ORDER_DATE,
    O.TOTAL_AMOUNT,
    ROW_NUMBER() OVER (
        PARTITION BY O.CUSTOMER_ID
        ORDER BY O.ORDER_DATE
    ) AS ORDER_SEQUENCE
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
ORDER BY
    O.CUSTOMER_ID, ORDER_SEQUENCE
LIMIT 50;


-- Query 31: Customer Revenue Quartile Segmentation using NTILE()
-- Business Question: Split customers into 4 equal revenue quartiles.
-- SQL Concept: NTILE(4) divides the result set into 4 equal buckets
-- ====================================================================
WITH CUSTOMER_SPEND AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.STATE,
        ROUND(SUM(O.TOTAL_AMOUNT), 2) AS TOTAL_SPENT
    FROM
        CUSTOMERS C
        JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE
        O.ORDER_STATUS != 'Cancelled'
    GROUP BY
        C.CUSTOMER_ID, C.CUSTOMER_NAME, C.STATE
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    STATE,
    TOTAL_SPENT,
    NTILE(4) OVER (ORDER BY TOTAL_SPENT DESC) AS REVENUE_QUARTILE,
    CASE NTILE(4) OVER (ORDER BY TOTAL_SPENT DESC)
        WHEN 1 THEN 'Top 25%'
        WHEN 2 THEN 'Upper Middle 25%'
        WHEN 3 THEN 'Lower Middle 25%'
        WHEN 4 THEN 'Bottom 25%'
    END AS QUARTILE_LABEL
FROM
    CUSTOMER_SPEND
ORDER BY
    TOTAL_SPENT DESC
LIMIT 30;


-- Query 32: Category-Level Product Ranking (RANK PARTITION BY)
-- Business Question: Rank products within each category by revenue.
-- SQL Concept: RANK() with PARTITION BY — separate ranking per group
-- ====================================================================
SELECT
    P.CATEGORY,
    P.PRODUCT_NAME,
    P.BRAND,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)   AS PRODUCT_REVENUE,
    RANK() OVER (
        PARTITION BY P.CATEGORY
        ORDER BY SUM(O.TOTAL_AMOUNT) DESC
    )                               AS RANK_IN_CATEGORY
FROM
    PRODUCTS P
    JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.CATEGORY, P.PRODUCT_NAME, P.BRAND
ORDER BY
    P.CATEGORY, RANK_IN_CATEGORY;


-- Query 33: Bottom 10 Products (Lowest Revenue)
-- Business Question: Which products are underperforming and may need attention?
-- SQL Concept: ORDER BY ASC to find lowest values
-- ====================================================================
SELECT
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    COUNT(DISTINCT O.ORDER_ID)       AS TOTAL_ORDERS,
    SUM(O.QUANTITY)                  AS UNITS_SOLD,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)    AS TOTAL_REVENUE
FROM
    PRODUCTS P
    JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.PRODUCT_NAME, P.CATEGORY, P.BRAND
ORDER BY
    TOTAL_REVENUE ASC
LIMIT 10;



-- ====================================================================
-- SECTION 9: WINDOW FUNCTIONS — RUNNING TOTALS & MOVING AVERAGE
-- SQL Concept: SUM OVER(), AVG OVER() with frame specification
-- ====================================================================


-- Query 34: Cumulative Revenue (Running Total by Month)
-- Business Question: How does revenue accumulate over the year?
-- SQL Concept: SUM() OVER (ORDER BY ...) — running total
-- ====================================================================
WITH MONTHLY AS (
    SELECT
        TO_CHAR(ORDER_DATE, 'YYYY-MM')    AS YEAR_MONTH,
        YEAR(ORDER_DATE)                   AS YEAR,
        MONTH(ORDER_DATE)                  AS MONTH,
        ROUND(SUM(TOTAL_AMOUNT), 2)        AS MONTHLY_REVENUE
    FROM
        ORDERS
    WHERE
        ORDER_STATUS != 'Cancelled'
    GROUP BY
        TO_CHAR(ORDER_DATE, 'YYYY-MM'),
        YEAR(ORDER_DATE),
        MONTH(ORDER_DATE)
)
SELECT
    YEAR_MONTH,
    MONTHLY_REVENUE,
    SUM(MONTHLY_REVENUE) OVER (
        ORDER BY YEAR, MONTH
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )                                     AS CUMULATIVE_REVENUE
FROM
    MONTHLY
ORDER BY
    YEAR, MONTH;


-- Query 35: 3-Month Moving Average Revenue
-- Business Question: What is the smoothed revenue trend (removes seasonality)?
-- SQL Concept: AVG OVER with ROWS BETWEEN frame — sliding window
-- ====================================================================
WITH MONTHLY AS (
    SELECT
        TO_CHAR(ORDER_DATE, 'YYYY-MM')    AS YEAR_MONTH,
        YEAR(ORDER_DATE)                   AS YEAR,
        MONTH(ORDER_DATE)                  AS MONTH,
        ROUND(SUM(TOTAL_AMOUNT), 2)        AS MONTHLY_REVENUE
    FROM
        ORDERS
    WHERE
        ORDER_STATUS != 'Cancelled'
    GROUP BY
        TO_CHAR(ORDER_DATE, 'YYYY-MM'),
        YEAR(ORDER_DATE),
        MONTH(ORDER_DATE)
)
SELECT
    YEAR_MONTH,
    MONTHLY_REVENUE,
    ROUND(AVG(MONTHLY_REVENUE) OVER (
        ORDER BY YEAR, MONTH
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2)                                 AS MOVING_AVG_3_MONTHS
FROM
    MONTHLY
ORDER BY
    YEAR, MONTH;


-- Query 36: Running Order Count per Customer (ROW_NUMBER as Running Count)
-- Business Question: Track the order journey of individual customers.
-- SQL Concept: ROW_NUMBER() as a running counter partitioned by customer
-- ====================================================================
SELECT
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.ORDER_DATE,
    O.TOTAL_AMOUNT,
    O.ORDER_STATUS,
    ROW_NUMBER() OVER (
        PARTITION BY O.CUSTOMER_ID
        ORDER BY O.ORDER_DATE
    )                                    AS NTH_ORDER,
    SUM(O.TOTAL_AMOUNT) OVER (
        PARTITION BY O.CUSTOMER_ID
        ORDER BY O.ORDER_DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )                                    AS RUNNING_CUSTOMER_SPEND
FROM
    ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY
    O.CUSTOMER_ID, NTH_ORDER
LIMIT 50;



-- ====================================================================
-- SECTION 10: ADVANCED BUSINESS ANALYTICS
-- SQL Concept: CASE WHEN, revenue contribution %, repeat analysis
-- ====================================================================


-- Query 37: Repeat vs One-Time Customer Analysis
-- Business Question: What percentage of customers are repeat buyers?
-- SQL Concept: CASE WHEN + COUNT + percentage
-- ====================================================================
WITH CUSTOMER_ORDER_COUNT AS (
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
    FROM
        ORDERS
    WHERE
        ORDER_STATUS != 'Cancelled'
    GROUP BY
        CUSTOMER_ID
)
SELECT
    COUNT(CUSTOMER_ID)                                 AS TOTAL_CUSTOMERS,
    COUNT(CASE WHEN ORDER_COUNT > 1 THEN 1 END)       AS REPEAT_CUSTOMERS,
    COUNT(CASE WHEN ORDER_COUNT = 1 THEN 1 END)       AS ONE_TIME_CUSTOMERS,
    ROUND(
        COUNT(CASE WHEN ORDER_COUNT > 1 THEN 1 END)
        * 100.0 / COUNT(CUSTOMER_ID), 2
    )                                                  AS REPEAT_CUSTOMER_PCT
FROM
    CUSTOMER_ORDER_COUNT;


-- Query 38: Customer Segmentation by Spending (CASE WHEN)
-- Business Question: How are our customers distributed across spending tiers?
-- SQL Concept: CASE WHEN for conditional bucket assignment
-- ====================================================================
SELECT
    CASE
        WHEN TOTAL_SPENT >= 500000 THEN 'Platinum (>= 5 Lakh)'
        WHEN TOTAL_SPENT >= 200000 THEN 'Gold (2–5 Lakh)'
        WHEN TOTAL_SPENT >= 50000  THEN 'Silver (50K–2 Lakh)'
        ELSE                            'Bronze (< 50K)'
    END                                                AS SEGMENT,
    COUNT(CUSTOMER_ID)                                 AS CUSTOMER_COUNT,
    ROUND(SUM(TOTAL_SPENT), 2)                         AS SEGMENT_REVENUE,
    ROUND(AVG(TOTAL_SPENT), 2)                         AS AVG_SPEND
FROM (
    SELECT
        C.CUSTOMER_ID,
        SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
    FROM
        CUSTOMERS C
        JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE
        O.ORDER_STATUS != 'Cancelled'
    GROUP BY
        C.CUSTOMER_ID
) CUSTOMER_TOTALS
GROUP BY
    SEGMENT
ORDER BY
    SEGMENT_REVENUE DESC;


-- Query 39: Revenue Contribution % by Category
-- Business Question: What share of total revenue does each category contribute?
-- SQL Concept: SUM OVER () for total + percentage calculation
-- ====================================================================
SELECT
    P.CATEGORY,
    ROUND(SUM(O.TOTAL_AMOUNT), 2)           AS CATEGORY_REVENUE,
    ROUND(
        SUM(O.TOTAL_AMOUNT) * 100.0 /
        SUM(SUM(O.TOTAL_AMOUNT)) OVER (), 2
    )                                        AS REVENUE_CONTRIBUTION_PCT,
    RANK() OVER (ORDER BY SUM(O.TOTAL_AMOUNT) DESC) AS CATEGORY_RANK
FROM
    ORDERS O
    JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    O.ORDER_STATUS != 'Cancelled'
GROUP BY
    P.CATEGORY
ORDER BY
    REVENUE_CONTRIBUTION_PCT DESC;


-- Query 40: Comprehensive Sales Dashboard Summary
-- Business Question: Single query for executive dashboard overview.
-- SQL Concept: Combining multiple metrics into one row using subqueries
-- ====================================================================
SELECT
    (SELECT COUNT(DISTINCT CUSTOMER_ID)
     FROM CUSTOMERS)                                            AS TOTAL_REGISTERED_CUSTOMERS,

    (SELECT COUNT(DISTINCT CUSTOMER_ID)
     FROM ORDERS
     WHERE ORDER_STATUS != 'Cancelled')                         AS ACTIVE_CUSTOMERS,

    (SELECT COUNT(DISTINCT PRODUCT_ID)
     FROM PRODUCTS)                                             AS TOTAL_PRODUCTS,

    (SELECT COUNT(DISTINCT ORDER_ID)
     FROM ORDERS)                                               AS TOTAL_ORDERS,

    (SELECT COUNT(DISTINCT ORDER_ID)
     FROM ORDERS
     WHERE ORDER_STATUS = 'Completed')                          AS COMPLETED_ORDERS,

    (SELECT ROUND(SUM(TOTAL_AMOUNT), 2)
     FROM ORDERS
     WHERE ORDER_STATUS = 'Completed')                          AS TOTAL_REVENUE_INR,

    (SELECT ROUND(AVG(TOTAL_AMOUNT), 2)
     FROM ORDERS
     WHERE ORDER_STATUS != 'Cancelled')                         AS AVG_ORDER_VALUE,

    (SELECT COUNT(DISTINCT CUSTOMER_ID)
     FROM (SELECT CUSTOMER_ID
           FROM ORDERS
           WHERE ORDER_STATUS != 'Cancelled'
           GROUP BY CUSTOMER_ID
           HAVING COUNT(DISTINCT ORDER_ID) > 1))                AS REPEAT_CUSTOMERS;
